env:
  global:
    secure: h0gIoDEXpLBTf3wEJBUaPKSintypyneNHiREB5bBWPjVmBF8CKnQDL4oUC00CNreki4Ti1NEA61I39Jx74BZl2yJtMoG4Vxavqe3JpJTJovocI84c0vmszYJWsbnsecNS0QeQYtHP5gU4ZstwGKjy4ddRUlt5BUE4FZPJI0vxOE=
addons:
  coverity_scan:
    project:
      name: woodjazz/nsg-library
      description: Build submitted via Travis CI
    notification_email: silveira.nestor@gmail.co
    build_command_prepend: "mkdir debug ; cd debug ; cmake .."
    build_command: make
    branch_pattern: coverity_scan

language:
- cpp
sudo: required
dist: trusty
os:
- linux
- osx
#matrix:
#  allow_failures:
#  - os: osx
compiler:
- gcc
- clang
git:
  submodules: false
before_install:
- export AUDIODEV=null
- export DISPLAY=:99.0
- #sh -e /etc/init.d/xvfb start
install:
- chmod +x travis_install.sh
- ./travis_install.sh
before_script:
- travis_retry git submodule update --init --recursive
script:
- chmod +x travis_script.sh
- if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./travis_script.sh ; fi

